name: Main workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      OUNIT_CI: true
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v1
      - name: Build
        run: opam exec -- dune build
      - name: Test
        run: opam exec -- dune runtest
